import path from 'node:path';
import { dirname } from 'path';
import genDiff from '../src/index.js';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const getFixturePath = (filename) => path.join(__dirname, '..', '__fixtures__', filename);
const path1 = getFixturePath('testPizza1.yml');
const path2 = getFixturePath('testPizza2.yaml');
const path3 = getFixturePath('testFile1.json');
const path4 = getFixturePath('testFile2.json');
const path5 = getFixturePath('empty.json');
const diff1 = (`{\n  - cheese: 3\n  + cheese: 4\n    meat: yes\n  - mushrooms: white\n  + mushrooms: lisichke\n  - testo: thin\n  + testo: crust\n}`);
const diff2 = (`{\n  - brain: undefined\n  - girls: cool\n  - http: hexlet.io\n  - ping: 125\n}`);
const diff3 = (`{\n\n}`);
test('genDiff', () => {
  expect(genDiff(path1,path2)).toEqual(diff1);
  expect(genDiff(path3,path4)).toEqual(diff2);
  expect(genDiff(path4,path5)).toEqual(diff3);
});